version: '3'
services:

    redis:
      image: redis:5-alpine
      container_name: app_redis
      restart: always
      ports:
        - 6379:6379
      networks:
        - backend
      command: "redis-server --requirepass ${REDIS_PASS}"

    backend:
      container_name: app_backend
      restart: always
      build: ./
      ports:
          - 8080:8080
      volumes:
          - ./backend:/app
          - ./docker/tmp/logs/:/usr/src/app/error.log
      networks:
          - backend
      command: ["pm2-runtime", "process.json"]

    # mongo:
    #     image: mongo
    #     container_name: app_mongo
    #     restart: always
    #     ports:
    #         - 27017:27017
    #     volumes:
    #         - ./docker/mongodb/data/db:/data/db
    #     networks:
    #         - backend

networks:
    backend:
