version: '3'
services:

    redis:
      image: redis:5-alpine
      container_name: app_redis
      restart: always
      ports:
        - 6379:6379
      networks:
        - edroh
      command: "redis-server --requirepass ${REDIS_PASS}"

    backend:
      container_name: app_backend
      restart: always
      build: ./
      ports:
          - 8080:8080
      volumes:
          - ./backend:/usr/src/app
      networks:
          - edroh
      command: ["pm2-runtime", "process.json"]

networks:
    edroh:
